### ISSUE TITLE
No tests found org.toradocu.PrecisionRecall*

### ISSUE THREAD

**Issue by JeewoongKim** [albertogoffi/toradocu#243] opened 2019-10-22 00:57 UTC
Jdoctor successfully runs on a single class (i.e., `net.Connection`) provided in the tutorial but, build failed to run on multiple classes with an exception.

Here are printed messages when running on the last instruction (`./gradlew test --tests "org.toradocu.PrecisionRecall*" -Dorg.toradocu.generator=true
`) in the tutorial.

messages:

>  What went wrong:
>  Execution failed for task ':test'.
>  No tests found for given includes: [org/toradocu/generator/**, org/toradocu/accuracy/paper/*](exclude rules) [org.toradocu.PrecisionRecall*](--tests filter)

Additionally, the released Toradocu (a.k.a Jdoctor) v3.0.tar.gz in [here](https://github.com/albertogoffi/toradocu/releases) seems to be different to git code. 
Because the released .tar even cannot run on a single class.

**Comment by ariannab** [comment] 2019-10-22 07:01
The issue is that those [tutorial](https://github.com/albertogoffi/toradocu/tree/master/tutorial) instructions have not been updated recently. 

Toradocu still works both on single and multiple classes, but not with the instructions reported there. 

> No tests found for given includes: [org/toradocu/generator/**, org/toradocu/accuracy/paper/](exclude rules) [org.toradocu.PrecisionRecall](--tests filter)

Yes: the tests have been later organized in subfolders, so there are no match in `org/toradocu/PrecisionRecall*`. Precision and recall tests are currently under [this](https://github.com/albertogoffi/toradocu/tree/master/src/test/java/org/toradocu/accuracy) folder.

> Additionally, the released Toradocu (a.k.a Jdoctor) v3.0.tar.gz in here seems to be different to git code. Because the released .tar even cannot run on a single class.

Yes, it is different. The version pointed there is the latest official release, i.e., the one described in the ISSTA 2018 paper. To run that version on a single class, you can check the paragraph _"Running Toradocu on any class"_ in the [artifact evaluation wiki](https://github.com/albertogoffi/toradocu/wiki/ISSTA-2018----Artifact-Evaluation). 
Note that version did not generate aspects, because the aspect generation was not part of the tool described in the paper. Currently the aspects generation works, but again, the tutorial should be updated with the instructions to use it.


Thank you for pointing the issue out, I will take care of the tutorial as soon as I can.

**Comment by ariannab** [comment] 2019-11-22 13:23
The tutorial page should now contain the correct information. I am closing this issue.

**Closed by ariannab** 2019-11-22 13:23 UTC
Labels: wiki
